### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by joshualaxamana** [mortend/android-build-tools#6]
This error shows whenever I run npm install android-build-tools

> android-build-tools@1.2.0 install C:\Users\Tagcash\AppData\Roaming\npm\node_modules\android-build-tools
> xbash install.bash

C:\Users\Tagcash\AppData\Roaming\npm\node_modules\android-build-tools\node_modules\xbash\index.js:47
    if (exe.toLowerCase() == exeInPATH.toLowerCase())
                                       ^

TypeError: Cannot read property 'toLowerCase' of null
    at addExeToPATH (C:\Users\Tagcash\AppData\Roaming\npm\node_modules\android-build-tools\node_modules\xbash\index.js:47:40)
    at Object.<anonymous> (C:\Users\Tagcash\AppData\Roaming\npm\node_modules\android-build-tools\node_modules\xbash\index.js:65:5)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Tagcash\AppData\Roaming\npm\node_modules\android-build-tools\node_modules\xbash\xbash.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! android-build-tools@1.2.0 install: `xbash install.bash`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the android-build-tools@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tagcash\AppData\Roaming\npm-cache\_logs\2019-12-05T09_22_41_423Z-debug.log
PS C:\Users\Tagcash>

**Comment by mortend** [comment]
Should be fixed now if you reinstall.
